DECISION_ARTICLES_A = {
    "access-control-pricing-commercial-building": {
        "published": "2025-10-08",
        "modified": "2025-10-08",
        "author": "L'équipe Opticable",
        "reading_minutes": 5,
        "related_services": ("access-control-systems", "intercom-systems", "structured-cabling"),
        "related_articles": ("access-control-vs-intercom", "camera-system-pricing-commercial-building"),
        "fr": {
            "path": "/fr/prix-controle-acces-immeuble-commercial/",
            "title": "Prix du contrôle d'accès commercial | Opticable",
            "desc": "Combien prévoir pour un système de contrôle d'accès commercial, ce qui fait varier la soumission et comment demander un prix réaliste.",
            "eyebrow": "Guide de prix",
            "headline": "Combien coûte un système de contrôle d'accès pour un immeuble commercial ?",
            "intro": "Réponse courte : pour une porte commerciale simple, il faut souvent prévoir environ 2 500 $ à 5 500 $. Dès qu'on passe à plusieurs portes, à une gestion centralisée, à des horaires d'accès, à un intercom ou à des contraintes de bâtiment occupé, le budget monte rapidement entre 6 000 $ et 20 000 $ et plus. Le vrai prix dépend surtout du nombre de portes, du type de quincaillerie, du câblage, du panneau de contrôle et du niveau de gestion demandé.",
            "excerpt": "Le prix d'un contrôle d'accès commercial dépend rarement du lecteur seulement. Les portes, la quincaillerie, le câblage et la gestion changent la vraie soumission.",
            "tags": ["Contrôle d'accès", "Soumission", "Immeuble commercial"],
            "primary_service": "access-control-systems",
            "related_resources": ("intercom-pricing-multi-tenant-building", "intercom-audio-or-video-commercial-building"),
            "summary": [
                ("Budget rapide", "Souvent 2 500 $ à 5 500 $ pour une porte simple, puis 6 000 $ et plus dès qu'il y a plusieurs portes ou une gestion plus poussée."),
                ("Ce qui fait varier le prix", "Le nombre de portes, la quincaillerie électrifiée, le câblage, les horaires, les accès visiteurs et la complexité du site."),
                ("Ce qu'il faut demander", "Une soumission qui détaille les portes, les lecteurs, le panneau, la quincaillerie, la programmation et les travaux de câblage."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "Le budget à retenir",
                    "paragraphs": [
                        "Le contrôle d'accès n'est pas un simple lecteur posé à côté d'une porte. Une vraie portée inclut la quincaillerie adaptée, le câblage de la porte, le panneau de contrôle, la programmation, les tests et la remise.",
                        "Une porte arrière simple dans un commerce ne se chiffre pas comme une entrée principale, une salle technique et plusieurs portes de circulation dans un immeuble occupé. Ce sont les portes et leurs conditions réelles qui dictent le prix.",
                    ],
                    "callout_label": "À retenir",
                    "callout": "Le meilleur réflexe est de penser en nombre de portes à contrôler, pas en prix par lecteur.",
                },
                {
                    "eyebrow": "Budgets types",
                    "title": "Ordres de grandeur selon la portée",
                    "table": {
                        "caption": "Budgets indicatifs pour un projet de contrôle d'accès",
                        "columns": ("Projet", "Portée typique", "Budget indicatif", "Quand ça s'applique"),
                        "rows": (
                            ("Porte simple", "1 porte, lecteur, gâche ou serrure, programmation de base", "2 500 $ à 5 500 $", "Commerce, bureau ou porte arrière avec besoin simple"),
                            ("Petit système", "2 à 4 portes avec gestion centralisée", "6 000 $ à 12 000 $", "Hall d'entrée, zones restreintes et circulation interne"),
                            ("Portée plus complète", "4 portes et plus, horaires, intégrations et visiteurs", "12 000 $ à 20 000 $ +", "Immeuble commercial, multilogement ou site multi-zones"),
                        ),
                    },
                },
                {
                    "eyebrow": "Variables",
                    "title": "Ce qui fait vraiment bouger la soumission",
                    "cards": [
                        ("Nombre de portes", "Chaque porte ajoute du câblage, de la quincaillerie, des raccordements et du temps d'installation."),
                        ("Type de quincaillerie", "Une gâche, un aimant, une serrure électrifiée ou une porte en aluminium ne demandent pas la même intervention."),
                        ("État des portes", "Certaines portes sont prêtes, d'autres exigent des ajustements mécaniques ou une coordination avec la porte elle-même."),
                        ("Gestion des accès", "Badges, horaires, groupes d'usagers et historique font monter la portée logicielle et la mise en service."),
                        ("Intégration", "Si l'accès doit travailler avec un intercom, des caméras ou une porte de garage, le projet devient plus large."),
                        ("Contraintes du site", "Bâtiment occupé, travaux par phases ou accès limités font monter le temps de coordination."),
                    ],
                },
                {
                    "eyebrow": "Avant de demander un prix",
                    "title": "Les informations qui accélèrent une vraie soumission",
                    "steps": [
                        ("Compter les portes visées", "Entrée principale, porte arrière, salle technique, entrepôt, suite ou porte de stationnement."),
                        ("Décrire l'usage de chaque porte", "Employés, locataires, visiteurs, livreurs ou zones restreintes n'impliquent pas la même logique."),
                        ("Confirmer les contraintes du site", "Bâtiment occupé, heures de travail, accès aux cadres et présence ou non d'un local technique."),
                        ("Préciser s'il faut une intégration", "Intercom, caméras, ouverture à distance ou administration multi-portes."),
                    ],
                    "quote": "Une bonne soumission d'accès commence toujours par une bonne lecture des portes.",
                },
            ],
            "faq_items": [
                ("Est-ce qu'on peut chiffrer juste par porte ?", "On peut donner un ordre de grandeur, mais un prix fiable dépend aussi de la quincaillerie, du cadre, du câblage et du type de gestion demandé."),
                ("Pourquoi une porte peut coûter beaucoup plus cher qu'une autre ?", "Parce qu'une porte simple déjà prête n'a rien à voir avec une porte en aluminium, une porte coupe-feu ou une porte qui exige des ajustements mécaniques."),
                ("Est-ce que le logiciel est inclus ?", "Ça dépend de la plateforme choisie et du type de gestion demandé. Il faut confirmer si la portée inclut les licences, l'administration et la programmation."),
                ("Quel est le meilleur moyen d'obtenir un prix utile ?", "Envoyez le nombre de portes, le type d'immeuble, l'usage des portes, les contraintes et les intégrations souhaitées. Une visite de site reste la meilleure base."),
            ],
            "cta": {
                "title": "Vous voulez un prix réaliste pour votre projet de contrôle d'accès ?",
                "copy": "Dites-nous combien de portes sont visées, le type d'immeuble et les contraintes du site. On vous revient avec une portée claire et les bons points à valider.",
                "primary_label": "Obtenir une soumission",
                "primary_key": "contact",
                "secondary_label": "Voir le service contrôle d'accès",
                "secondary_key": "access-control-systems",
            },
        },
    },
    "intercom-pricing-multi-tenant-building": {
        "published": "2025-11-06",
        "modified": "2025-11-06",
        "author": "Yan-Erik B.",
        "reading_minutes": 4,
        "related_services": ("intercom-systems", "access-control-systems", "structured-cabling"),
        "related_articles": ("access-control-vs-intercom",),
        "fr": {
            "path": "/fr/prix-intercom-immeuble-multilogement/",
            "title": "Prix d'un intercom pour immeuble multilogement | Opticable",
            "desc": "Combien prévoir pour un intercom audio ou vidéo dans un immeuble multilogement et ce qui change vraiment la soumission.",
            "eyebrow": "Guide de prix",
            "headline": "Combien coûte un intercom pour un immeuble multilogement ?",
            "intro": "Réponse courte : un intercom simple pour une entrée principale peut souvent commencer autour de 3 000 $ à 6 000 $. Un système vidéo plus complet, avec ouverture de porte, gestion plus propre des visiteurs, plusieurs entrées ou intégration au contrôle d'accès, monte souvent entre 7 000 $ et 18 000 $ et plus. Le vrai prix dépend du nombre d'entrées, du type de communication voulu, du câblage à reprendre et du niveau d'intégration.",
            "excerpt": "Le prix d'un intercom dépend surtout du type d'entrée, du nombre d'entrées, du câblage et du niveau d'intégration avec l'accès.",
            "tags": ["Intercom", "Immeuble multilogement", "Soumission"],
            "primary_service": "intercom-systems",
            "related_resources": ("intercom-audio-or-video-commercial-building", "access-control-pricing-commercial-building"),
            "summary": [
                ("Budget rapide", "Souvent 3 000 $ à 6 000 $ pour une portée simple, puis 7 000 $ et plus dès qu'il y a vidéo, plusieurs entrées ou intégration."),
                ("Ce qui fait varier le prix", "Audio ou vidéo, une ou plusieurs entrées, ouverture de porte, câblage existant et logique visiteurs-locataires."),
                ("Ce qu'il faut valider", "Le nombre d'entrées, le type d'immeuble, le nombre d'occupants et la manière d'ouvrir la porte."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "Ce qu'on paie vraiment dans un projet d'intercom",
                    "paragraphs": [
                        "Un intercom n'est pas seulement un panneau d'entrée. Il faut considérer l'appel, la communication, l'ouverture de porte, l'alimentation, le câblage, le raccordement réseau si requis et la remise en service complète.",
                        "Dans un immeuble multilogement, le prix varie vite si l'entrée doit gérer plusieurs occupants, des visiteurs, une ouverture à distance ou plusieurs points d'accès.",
                    ],
                    "callout_label": "Raccourci utile",
                    "callout": "Plus il y a d'entrées, de locataires et de fonctions d'ouverture, plus la soumission se rapproche d'un vrai système d'entrée et pas juste d'un poste d'appel.",
                },
                {
                    "eyebrow": "Budgets types",
                    "title": "Ordres de grandeur fréquents",
                    "table": {
                        "caption": "Budgets indicatifs pour un intercom multilogement",
                        "columns": ("Projet", "Portée typique", "Budget indicatif", "Quand ça s'applique"),
                        "rows": (
                            ("Audio simple", "1 entrée, appel de base, ouverture de porte", "3 000 $ à 6 000 $", "Petit immeuble ou besoin fonctionnel sans vidéo"),
                            ("Vidéo simple", "1 entrée vidéo avec meilleure validation visiteur", "5 500 $ à 9 500 $", "Immeuble qui veut mieux filtrer les visiteurs"),
                            ("Portée plus complète", "Plusieurs entrées, intégration à l'accès ou logique plus avancée", "9 000 $ à 18 000 $ +", "Immeuble plus grand, plusieurs entrées ou exigence de gestion plus poussée"),
                        ),
                    },
                },
                {
                    "eyebrow": "Variables",
                    "title": "Les facteurs qui changent le prix",
                    "cards": [
                        ("Audio ou vidéo", "La vidéo améliore la validation, mais elle fait monter le matériel, le réseau et la mise en service."),
                        ("Nombre d'entrées", "Une seule entrée principale n'a rien à voir avec deux halls, un stationnement ou une porte secondaire."),
                        ("Ouverture de porte", "Déverrouillage, gâche, serrure ou intégration avec l'accès changent la quincaillerie et le câblage."),
                        ("Câblage existant", "Un ancien système ou un câblage à reprendre peut faire varier la portée plus que le panneau lui-même."),
                        ("Mode de réponse", "Poste intérieur, téléphone mobile ou logique mixte changent le type de système proposé."),
                        ("Base réseau et distribution", "Quand le local réseau, le PoE, le commutateur ou les câbles entre étages doivent être repris, la soumission augmente vite."),
                        ("Bâtiment occupé", "Travaux dans un hall actif, coordination avec les occupants et accès limités font bouger la main-d'oeuvre."),
                    ],
                },
                {
                    "eyebrow": "Réseau et câblage",
                    "title": "L'intercom dépend souvent de la base réseau du bâtiment",
                    "paragraphs": [
                        "Dans un immeuble multilogement, un intercom vidéo ou connecté ne s'arrête pas au panneau d'entrée. Il faut parfois reprendre l'alimentation, le câblage, le point de raccordement, le commutateur PoE ou la distribution entre l'entrée et le local réseau principal.",
                        "Plus le bâtiment a d'entrées, d'étages ou de logique d'ouverture à distance, plus il faut valider la base réseau, le câblage entre étages et la place disponible dans le local technique avant de parler d'un vrai prix.",
                    ],
                    "callout_label": "À retenir",
                    "callout": "Un bon prix d'intercom tient compte du panneau d'entrée, mais aussi de la base réseau et du câblage qui permettent au système de fonctionner proprement.",
                },
                {
                    "eyebrow": "Préparation",
                    "title": "Ce qu'il faut indiquer avant une demande de prix",
                    "steps": [
                        ("Combien d'entrées sont visées ?", "Entrée principale seulement, stationnement, porte arrière ou accès secondaires."),
                        ("Quel type d'occupants ?", "Locataires, copropriétaires, bureaux, commerces ou usage mixte."),
                        ("Faut-il seulement parler ou aussi déverrouiller ?", "La logique d'ouverture change tout dans la portée."),
                        ("Le système doit-il travailler avec l'accès ?", "Si oui, il faut le dire dès le départ pour cadrer le bon scénario."),
                        ("Le câblage et le local réseau sont-ils déjà prêts ?", "Un ancien intercom, un rack encombré ou des câbles à reprendre font souvent varier la soumission."),
                    ],
                    "quote": "Dans un immeuble multilogement, un intercom utile est celui qui suit la vraie logique d'entrée du bâtiment.",
                },
            ],
            "faq_items": [
                ("Un intercom audio est-il encore suffisant ?", "Oui, dans certains petits immeubles ou pour une logique simple. Dès qu'il faut mieux filtrer les visiteurs, la vidéo apporte une vraie valeur."),
                ("Est-ce que l'intercom peut ouvrir la porte ?", "Oui, si la portée inclut la quincaillerie et la logique d'ouverture adaptées."),
                ("Pourquoi le nombre de logements ne suffit-il pas pour chiffrer ?", "Parce que le prix dépend surtout des entrées, du câblage, du type de communication et de la logique d'ouverture, pas seulement du nombre d'unités."),
                ("Quel est le meilleur point de départ pour une soumission ?", "Envoyez le type d'immeuble, le nombre d'entrées, le type d'occupants et ce qui ne fonctionne plus ou ce que vous voulez améliorer."),
            ],
            "cta": {
                "title": "Vous voulez chiffrer un intercom pour votre immeuble ?",
                "copy": "Décrivez le type d'immeuble, le nombre d'entrées et le type d'ouverture souhaité. On vous dira rapidement quelle portée prévoir.",
                "primary_label": "Obtenir une soumission",
                "primary_key": "contact",
                "secondary_label": "Voir le service intercom",
                "secondary_key": "intercom-systems",
            },
        },
    },
    "intercom-audio-or-video-commercial-building": {
        "published": "2025-12-04",
        "modified": "2025-12-04",
        "author": "L'équipe Opticable",
        "reading_minutes": 4,
        "related_services": ("intercom-systems", "access-control-systems", "security-camera-systems"),
        "related_articles": ("access-control-vs-intercom",),
        "fr": {
            "path": "/fr/intercom-audio-ou-video-immeuble-commercial/",
            "title": "Intercom audio ou vidéo pour immeuble commercial | Opticable",
            "desc": "Comment choisir entre un intercom audio et un intercom vidéo pour une entrée commerciale ou multilocative.",
            "eyebrow": "Guide de décision",
            "headline": "Intercom audio ou vidéo : lequel choisir pour un immeuble commercial ?",
            "intro": "Réponse courte : l'audio suffit encore quand il faut simplement parler à un visiteur et ouvrir une porte de façon fonctionnelle. La vidéo devient vite préférable quand il faut mieux valider qui se présente, gérer des visiteurs inconnus, limiter les erreurs d'ouverture ou intégrer plus proprement l'entrée avec l'accès et la sécurité. Le bon choix dépend du type d'immeuble, du flux de visiteurs et du niveau de contrôle attendu.",
            "excerpt": "Audio pour une logique simple, vidéo pour une meilleure validation. Le bon choix dépend surtout du flux de visiteurs et du niveau de contrôle recherché.",
            "tags": ["Intercom", "Entrée sécurisée", "Immeuble commercial"],
            "primary_service": "intercom-systems",
            "related_resources": ("intercom-pricing-multi-tenant-building", "access-control-pricing-commercial-building"),
            "summary": [
                ("Audio", "Bon choix pour une entrée simple avec peu de visiteurs et une logique directe."),
                ("Vidéo", "Mieux quand il faut valider visuellement les visiteurs et réduire les erreurs."),
                ("Le bon critère", "La décision dépend du risque, du volume de visiteurs et de la manière de gérer l'entrée."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "L'audio et la vidéo ne règlent pas le même niveau de risque",
                    "paragraphs": [
                        "Un intercom audio permet de parler à la personne qui sonne et de décider si on ouvre. C'est souvent suffisant pour une petite entrée ou un site où les visiteurs sont déjà connus.",
                        "Un intercom vidéo ajoute une validation visuelle. Cette différence devient importante dans les halls principaux, les immeubles avec beaucoup de visiteurs, les accès partagés ou les situations où ouvrir la mauvaise porte a un vrai coût.",
                    ],
                    "callout_label": "Décision rapide",
                    "callout": "Si la question est surtout parler ou ouvrir, l'audio peut suffire. Si la question est aussi confirmer qui est là, la vidéo devient la meilleure option.",
                },
                {
                    "eyebrow": "Comparatif",
                    "title": "Comparatif simple",
                    "table": {
                        "caption": "Audio ou vidéo selon le contexte",
                        "columns": ("Critère", "Audio", "Vidéo"),
                        "rows": (
                            ("Coût initial", "Plus bas", "Plus élevé"),
                            ("Validation du visiteur", "Limitée à la voix", "Validation visuelle plus claire"),
                            ("Halls actifs et visiteurs inconnus", "Moins adapté", "Mieux adapté"),
                            ("Expérience utilisateur", "Fonctionnelle", "Plus rassurante et plus claire"),
                            ("Intégration sécurité", "Possible mais plus simple", "Plus naturelle avec l'accès et les caméras"),
                        ),
                    },
                },
                {
                    "eyebrow": "Quand choisir",
                    "title": "Les cas les plus fréquents",
                    "cards": [
                        ("Audio", "Petite entrée, faible volume de visiteurs, besoin fonctionnel et budget serré."),
                        ("Vidéo", "Hall principal, visiteurs fréquents, immeuble multilogement ou besoin de mieux filtrer."),
                        ("Vidéo + accès", "Immeuble qui veut gérer visiteurs, résidents ou employés dans une logique plus unifiée."),
                    ],
                },
                {
                    "eyebrow": "Avant de choisir",
                    "title": "Les questions à se poser",
                    "steps": [
                        ("Qui se présente à l'entrée ?", "Visiteurs connus, livreurs, résidents, clients ou fournisseurs."),
                        ("À quel point l'erreur coûte cher ?", "Ouvrir à la mauvaise personne n'a pas le même impact partout."),
                        ("Combien d'entrées sont concernées ?", "Une entrée unique et un site avec plusieurs points d'accès n'ont pas les mêmes besoins."),
                        ("Faut-il intégrer l'intercom à l'accès ?", "Si oui, la vidéo devient souvent plus logique dès le départ."),
                    ],
                    "quote": "Le bon choix n'est pas audio ou vidéo en général. Le bon choix, c'est ce qui correspond au vrai risque à l'entrée.",
                },
            ],
            "faq_items": [
                ("La vidéo est-elle toujours meilleure ?", "Pas automatiquement. Si l'entrée est simple et que les visiteurs sont connus, l'audio peut être suffisant et plus économique."),
                ("La vidéo ralentit-elle l'installation ?", "Pas nécessairement, mais elle ajoute du matériel, du réseau et parfois une intégration plus poussée."),
                ("Peut-on passer d'audio à vidéo plus tard ?", "Oui, dans certains cas, mais il vaut mieux le prévoir dès le départ si le besoin est déjà probable."),
                ("Quel choix faites-vous le plus souvent ?", "Dans les halls principaux et les immeubles partagés, la vidéo est souvent le meilleur compromis entre sécurité, clarté et gestion."),
            ],
            "cta": {
                "title": "Vous hésitez entre audio et vidéo ?",
                "copy": "Décrivez votre entrée, le type de visiteurs et le type d'immeuble. On vous dira rapidement quelle option fait le plus de sens.",
                "primary_label": "Parler de mon projet",
                "primary_key": "contact",
                "secondary_label": "Voir le service intercom",
                "secondary_key": "intercom-systems",
            },
        },
    },
}
