DECISION_ARTICLES_B = {
    "structured-cabling-pricing-office-retail": {
        "published": "2026-01-09",
        "modified": "2026-01-09",
        "author": "Yan-Erik B.",
        "reading_minutes": 5,
        "related_services": ("structured-cabling", "network-infrastructure", "fiber-optic-installation"),
        "related_articles": ("structured-cabling-foundation", "cat6a-or-fiber-commercial-building"),
        "fr": {
            "path": "/fr/prix-cablage-structure-bureau-commerce/",
            "title": "Prix de câblage structuré pour bureau ou commerce | Opticable",
            "desc": "Combien prévoir pour du câblage structuré commercial, l'ajout de prises réseau et la remise en ordre d'un environnement existant.",
            "eyebrow": "Guide de prix",
            "headline": "Combien coûte du câblage structuré dans un bureau ou un commerce ?",
            "intro": "Réponse courte : pour quelques nouvelles prises réseau dans un petit local, il faut souvent prévoir quelques centaines à quelques milliers de dollars selon les parcours. Pour une portée plus complète avec plusieurs prises, rack, panneaux de brassage, tests et remise en ordre, le budget grimpe vite entre 3 000 $ et 15 000 $ et plus. Le vrai prix dépend surtout du nombre de prises à ajouter, des cheminements, de l'état du local réseau et du niveau de finition demandé.",
            "excerpt": "Le prix du câblage structuré dépend du nombre de prises, des parcours, du rack et de l'état réel du site beaucoup plus que du câble lui-même.",
            "tags": ["Câblage structuré", "Prises réseau", "Soumission"],
            "primary_service": "structured-cabling",
            "related_resources": ("network-room-rack-cleanup", "access-control-pricing-commercial-building"),
            "summary": [
                ("Budget rapide", "Quelques prises réseau coûtent une chose. Une vraie base structurée avec rack, brassage et tests en coûte une autre."),
                ("Ce qui fait varier le prix", "Les parcours, les plafonds, le nombre de prises, l'état du rack et les travaux de finition."),
                ("Ce qu'il faut demander", "Une soumission qui distingue les prises, les chemins, le brassage, les tests et la documentation."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "Ce qu'on chiffre dans un projet de câblage",
                    "paragraphs": [
                        "Le câble lui-même n'est qu'une partie du projet. Le vrai coût vient des parcours, des plafonds, des percements, du brassage, du repérage, des tests et de la qualité de la remise.",
                        "Ajouter trois prises dans un petit local déjà bien organisé n'a rien à voir avec remettre propre un rack, reprendre des parcours et amener quinze nouvelles prises dans un commerce en activité.",
                    ],
                    "callout_label": "Point clé",
                    "callout": "Le bon budget de câblage se pense en portée complète, pas seulement en nombre de mètres de câble.",
                },
                {
                    "eyebrow": "Budgets types",
                    "title": "Ordres de grandeur fréquents",
                    "table": {
                        "caption": "Budgets indicatifs pour du câblage structuré commercial",
                        "columns": ("Projet", "Portée typique", "Budget indicatif", "Quand ça s'applique"),
                        "rows": (
                            ("Ajouts simples", "Quelques prises réseau dans un local ou un petit bureau", "500 $ à 2 500 $", "Ajout ciblé avec parcours accessibles"),
                            ("Portée intermédiaire", "Plusieurs prises, brassage et meilleure organisation", "3 000 $ à 8 000 $", "Bureau, commerce ou aire de travail en croissance"),
                            ("Portée complète", "Prises, rack, panneaux, remise en ordre et tests", "8 000 $ à 15 000 $ +", "Projet plus structuré ou environnement existant à reprendre"),
                        ),
                    },
                },
                {
                    "eyebrow": "Variables",
                    "title": "Ce qui fait bouger la soumission",
                    "cards": [
                        ("Nombre de prises", "Plus il y a de prises à ajouter, plus il faut de parcours, de brassage et de temps de test."),
                        ("Accessibilité", "Plafonds ouverts, plénums chargés, murs finis et distances longues changent beaucoup la main-d'oeuvre."),
                        ("État du rack", "Un rack ou un local réseau mal organisé ajoute souvent du temps avant même le premier nouveau câble."),
                        ("Catégorie de câble", "Cat6 et Cat6A n'impliquent pas toujours la même rigidité, les mêmes contraintes et le même temps de finition."),
                        ("Finition attendue", "Repérage, tests, brassage propre et documentation claire font partie d'une vraie remise."),
                        ("Travaux en site occupé", "Commerce ouvert, bureau actif ou horaires limités changent la planification."),
                    ],
                },
                {
                    "eyebrow": "Préparation",
                    "title": "Ce qu'il faut envoyer pour obtenir un prix utile",
                    "steps": [
                        ("Combien de prises faut-il ajouter ?", "Donnez un nombre approximatif, même si ce n'est pas exact."),
                        ("Où vont-elles ?", "Postes de travail, caisse, borne WiFi, caméra, téléphone IP ou salle de réunion."),
                        ("Quel est l'état du local réseau ?", "Y a-t-il un rack, des panneaux de brassage et de la place disponible ?"),
                        ("Le site est-il occupé ?", "Bureau en service, commerce ouvert ou chantier en cours changent la planification."),
                    ],
                    "quote": "Dans le câblage commercial, la qualité de la remise vaut souvent autant que le tirage lui-même.",
                },
            ],
            "faq_items": [
                ("Peut-on demander un prix par prise réseau ?", "On peut donner un ordre de grandeur, mais le vrai prix dépend surtout des parcours, de l'accès et de l'état du local réseau."),
                ("Cat6A coûte-t-il beaucoup plus cher ?", "Il peut coûter plus cher en matériel et en installation selon les distances et la densité, mais il n'est pas nécessaire partout."),
                ("Le rack et les panneaux de brassage sont-ils toujours inclus ?", "Pas automatiquement. Il faut confirmer si la portée inclut seulement les prises ou aussi l'organisation complète côté local réseau."),
                ("Quel est le meilleur point de départ ?", "Envoyez le nombre approximatif de prises, le type de site, les zones visées et quelques photos du local réseau si possible."),
            ],
            "cta": {
                "title": "Vous voulez chiffrer du câblage structuré ?",
                "copy": "Dites-nous combien de prises il faut ajouter, où elles vont et dans quel type d'environnement. On vous dira rapidement quelle portée prévoir.",
                "primary_label": "Obtenir une soumission",
                "primary_key": "contact",
                "secondary_label": "Voir le service câblage",
                "secondary_key": "structured-cabling",
            },
        },
    },
    "analog-cctv-to-ip-migration": {
        "published": "2026-02-06",
        "modified": "2026-02-06",
        "author": "L'équipe Opticable",
        "reading_minutes": 5,
        "related_services": ("security-camera-systems", "network-infrastructure", "structured-cabling"),
        "related_articles": ("ip-cameras-network-upgrade", "camera-system-pricing-commercial-building"),
        "fr": {
            "path": "/fr/migration-cameras-analogiques-vers-ip/",
            "title": "Migration de caméras analogiques vers IP | Opticable",
            "desc": "Quand remplacer un vieux système de caméras analogiques par un système IP, ce qu'on peut garder et ce qu'il faut planifier.",
            "eyebrow": "Guide de migration",
            "headline": "Comment planifier une migration de caméras analogiques vers IP",
            "intro": "Réponse courte : on ne remplace pas un vieux système analogique seulement parce qu'il est vieux. On le remplace quand la qualité d'image ne suit plus, que le visionnement à distance devient limité, que la maintenance coûte trop cher ou que le réseau du bâtiment est rendu capable de supporter une meilleure portée. Dans plusieurs projets, on peut migrer par phases, garder certaines portions temporairement et planifier la vraie base IP sans tout jeter d'un coup.",
            "excerpt": "Une migration vers IP se planifie par réseau, stockage, câblage et priorités du site, pas juste par remplacement de caméras.",
            "tags": ["Caméras de sécurité", "Migration", "Réseau"],
            "primary_service": "security-camera-systems",
            "related_resources": ("access-control-pricing-commercial-building", "network-room-rack-cleanup"),
            "summary": [
                ("Quand migrer", "Quand l'image, l'accès à distance, la maintenance ou l'évolution du système ne suivent plus."),
                ("Ce qu'on peut parfois garder", "Certaines portions de câblage ou une migration par phases, selon l'état réel du site."),
                ("Ce qu'il faut valider", "Le réseau, le PoE, le stockage, les zones prioritaires et l'ordre de migration."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "La vraie question n'est pas analogique ou IP",
                    "paragraphs": [
                        "La vraie question est plutôt : est-ce que votre système actuel répond encore aux besoins du bâtiment ? Si la réponse est non, la migration vers IP devient souvent la prochaine étape logique.",
                        "Les limites reviennent toujours aux mêmes endroits : qualité d'image, difficulté d'accès à distance, peu de souplesse pour ajouter des caméras et manque d'intégration avec le reste du site.",
                    ],
                    "callout_label": "Le bon réflexe",
                    "callout": "Une migration IP réussie commence par les zones prioritaires et la base réseau, pas par une liste d'appareils.",
                },
                {
                    "eyebrow": "Quand migrer",
                    "title": "Les signaux qui montrent qu'il faut avancer",
                    "cards": [
                        ("Image insuffisante", "Les événements ne sont pas assez exploitables ou les zones critiques restent trop floues."),
                        ("Visionnement limité", "L'accès à distance est compliqué, instable ou trop limité pour les vrais besoins du site."),
                        ("Système figé", "Ajouter ou déplacer une caméra devient coûteux ou peu logique dans l'architecture actuelle."),
                        ("Maintenance lourde", "On passe trop de temps à faire survivre un système ancien au lieu de l'exploiter."),
                        ("Site modernisé", "Le bâtiment a déjà évolué en réseau, en WiFi ou en accès, mais la surveillance reste en arrière."),
                        ("Besoin d'intégration", "Le site veut mieux aligner la surveillance avec l'accès, les alertes ou la gestion à distance."),
                    ],
                },
                {
                    "eyebrow": "Planification",
                    "title": "Ce qu'il faut valider avant de migrer",
                    "steps": [
                        ("Lister les zones prioritaires", "Entrées, stationnement, quai, corridors, caisse ou local technique."),
                        ("Vérifier la base réseau", "PoE, commutateurs, rack, uplinks et marge disponible pour soutenir les nouvelles caméras."),
                        ("Évaluer le câblage existant", "Certaines portions peuvent parfois être gardées temporairement, d'autres doivent être reprises."),
                        ("Choisir la stratégie", "Migration complète, par phases ou remplacement ciblé des zones critiques en premier."),
                    ],
                    "quote": "La migration IP se réussit quand elle améliore l'exploitation du site, pas seulement quand elle remplace l'ancien matériel.",
                },
                {
                    "eyebrow": "Budget",
                    "title": "Ce qui fait varier le projet",
                    "table": {
                        "caption": "Les grands postes qui bougent dans une migration caméra",
                        "columns": ("Élément", "Faible impact", "Impact plus fort"),
                        "rows": (
                            ("Câblage", "Parcours accessibles et base réutilisable", "Parcours à reprendre et zones difficiles"),
                            ("Réseau", "Rack et PoE déjà prêts", "Commutateurs, PoE et organisation à remettre au propre"),
                            ("Stockage", "Peu de caméras et rétention simple", "Plusieurs caméras, longue rétention et besoins de consultation"),
                            ("Déploiement", "Site simple et accessible", "Bâtiment occupé, travaux par phases ou heures limitées"),
                        ),
                    },
                },
            ],
            "faq_items": [
                ("Faut-il tout remplacer d'un coup ?", "Pas toujours. Plusieurs projets se font par phases, en traitant les zones critiques d'abord."),
                ("Peut-on garder une partie du câblage ?", "Parfois oui, selon l'état réel, les parcours et la stratégie choisie. Il faut le valider sur place."),
                ("Pourquoi le réseau compte-t-il autant ?", "Parce qu'une caméra IP dépend du PoE, du câblage, du brassage, du stockage et d'un environnement réseau propre."),
                ("Quel est le meilleur point de départ ?", "Envoyez les zones à moderniser, l'état actuel du système et quelques photos du local réseau si possible."),
            ],
            "cta": {
                "title": "Vous pensez migrer un vieux système de caméras ?",
                "copy": "Décrivez le type de site, les zones prioritaires et l'état du système actuel. On vous dira comment cadrer une migration réaliste.",
                "primary_label": "Parler de mon projet",
                "primary_key": "contact",
                "secondary_label": "Voir le service caméras",
                "secondary_key": "security-camera-systems",
            },
        },
    },
    "network-room-rack-cleanup": {
        "published": "2026-03-05",
        "modified": "2026-03-05",
        "author": "Yan-Erik B.",
        "reading_minutes": 4,
        "related_services": ("network-infrastructure", "structured-cabling", "commercial-wifi-installation"),
        "related_articles": ("structured-cabling-foundation", "commercial-wifi-audit-checklist"),
        "fr": {
            "path": "/fr/remise-en-ordre-local-reseau-et-rack/",
            "title": "Remise en ordre d'un local réseau et d'un rack | Opticable",
            "desc": "Quand remettre au propre un rack ou un local réseau, ce qu'on corrige et pourquoi ça change la suite des projets.",
            "eyebrow": "Guide pratique",
            "headline": "Quand faut-il remettre en ordre un local réseau ou un rack ?",
            "intro": "Réponse courte : dès qu'un local réseau ralentit les interventions, complique les ajouts, empêche de voir clair dans le brassage ou fait perdre du temps au moindre problème, il faut le reprendre. Une remise en ordre n'est pas juste visuelle. C'est souvent ce qui permet ensuite d'ajouter du WiFi, des caméras, du contrôle d'accès ou de nouvelles prises sans repartir dans le chaos.",
            "excerpt": "Un rack désorganisé fait perdre du temps, augmente le risque d'erreur et complique chaque nouveau projet. Le remettre propre est souvent la vraie première étape.",
            "tags": ["Infrastructure réseau", "Rack", "Local réseau"],
            "primary_service": "network-infrastructure",
            "related_resources": ("structured-cabling-pricing-office-retail", "analog-cctv-to-ip-migration"),
            "summary": [
                ("Quand agir", "Quand le brassage est confus, que les interventions prennent trop de temps ou qu'un nouveau projet approche."),
                ("Ce qu'on corrige", "Patch panels, brassage, identification, alimentation, organisation du rack et logique du local."),
                ("Le gain", "Des ajouts et du support plus rapides, plus propres et moins risqués."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "Un rack propre n'est pas une question d'esthétique",
                    "paragraphs": [
                        "Un local réseau mal organisé devient vite un frein opérationnel. Chaque ajout, panne ou modernisation prend plus de temps, crée plus de risque et coûte plus cher.",
                        "À l'inverse, un rack propre permet de savoir rapidement ce qui est en service, ce qui est libre, où passent les liens et comment soutenir la suite du site sans improviser.",
                    ],
                    "callout_label": "À retenir",
                    "callout": "Dans beaucoup de projets, remettre le local réseau au propre est la première vraie étape avant d'ajouter quoi que ce soit.",
                },
                {
                    "eyebrow": "Signaux d'alerte",
                    "title": "Les signes qu'il faut intervenir",
                    "items": [
                        "Patch cords enchevêtrés et non identifiés",
                        "Aucune logique claire entre les prises et les panneaux de brassage",
                        "Commutateurs sans marge visible ou sans organisation de ports",
                        "Ajouts faits au fil du temps sans vraie remise au propre",
                        "Impossible de savoir rapidement ce qui alimente quoi",
                        "Nouveau projet à venir : WiFi, caméras, accès, téléphonie ou expansion du site",
                    ],
                },
                {
                    "eyebrow": "Ce qu'on reprend",
                    "title": "Ce qu'une remise en ordre peut inclure",
                    "cards": [
                        ("Organisation physique", "Rangement du rack, gestion des câbles, meilleure répartition et accès plus clair."),
                        ("Repérage", "Identification des prises, des panneaux, des uplinks et des équipements critiques."),
                        ("Brassage", "Reprise des patch cords et clarification des liens actifs."),
                        ("Marge pour la suite", "Préparation du rack pour les futurs ajouts plutôt que simple nettoyage ponctuel."),
                        ("Validation", "Lecture de ce qui est encore utile, de ce qui est obsolète et de ce qui doit être déplacé."),
                        ("Documentation de base", "Remise d'un environnement plus compréhensible pour la suite du support."),
                    ],
                },
                {
                    "eyebrow": "Le bon moment",
                    "title": "Quand le faire",
                    "steps": [
                        ("Avant un projet", "Avant d'ajouter du WiFi, des caméras, de l'accès ou de nouvelles prises réseau."),
                        ("Avant un déménagement ou une expansion", "Quand le site s'agrandit ou que l'organisation du bureau change."),
                        ("Quand le support devient trop lourd", "Quand chaque dépannage demande trop de temps juste pour lire le local."),
                        ("Quand personne ne veut y toucher", "Souvent, c'est déjà le signe qu'il faut intervenir."),
                    ],
                    "quote": "Un local réseau bien repris devient une base de projet. Un local laissé au hasard devient une dette technique.",
                },
            ],
            "faq_items": [
                ("Est-ce que vous faites ça sans tout remplacer ?", "Oui. Le but est souvent de remettre logique et lisibilité avant de décider ce qui doit vraiment être changé."),
                ("Est-ce que ça vaut la peine avant un projet WiFi ou caméras ?", "Oui, très souvent. Une base propre simplifie beaucoup l'ajout des nouveaux systèmes."),
                ("Est-ce que c'est seulement pour les gros sites ?", "Non. Même un petit rack peut devenir un problème s'il a été modifié sans structure pendant des années."),
                ("Qu'est-ce qui aide à cadrer la portée ?", "Quelques photos du rack, le type de site et le projet à venir suffisent souvent pour commencer."),
            ],
            "cta": {
                "title": "Votre local réseau est devenu un obstacle ?",
                "copy": "Envoyez-nous quelques photos et décrivez ce que vous voulez ajouter ensuite. On vous dira si une remise en ordre doit venir avant le reste.",
                "primary_label": "Demander une évaluation",
                "primary_key": "contact",
                "secondary_label": "Voir le service infrastructure réseau",
                "secondary_key": "network-infrastructure",
            },
        },
    },
}
