GUIDE_ARTICLES = {
    "camera-system-pricing-commercial-building": {
        "published": "2025-12-09",
        "modified": "2025-12-09",
        "author": "L'équipe Opticable",
        "reading_minutes": 5,
        "related_services": ("security-camera-systems", "structured-cabling", "network-infrastructure"),
        "related_articles": ("ip-cameras-network-upgrade", "structured-cabling-foundation"),
        "fr": {
            "path": "/fr/prix-systeme-cameras-immeuble-commercial/",
            "title": "Prix d'un système de caméras pour immeuble commercial | Opticable",
            "desc": "Combien prévoir pour un système de caméras dans un immeuble commercial, ce qui fait varier la soumission et comment obtenir un prix réaliste.",
            "eyebrow": "Guide d'achat",
            "headline": "Combien coûte un système de caméras pour un immeuble commercial ?",
            "intro": "Réponse courte : pour un petit immeuble commercial, il faut souvent prévoir environ 3 500 $ à 7 500 $ pour une portée simple. Un système plus complet avec davantage de caméras, un NVR, du PoE, du câblage et des zones extérieures monte souvent entre 8 000 $ et 25 000 $ et plus. Le vrai prix dépend surtout du nombre de caméras à installer, des parcours de câblage, des accès au bâtiment, du stockage vidéo et du niveau de finition demandé.",
            "excerpt": "Un système de caméras commercial ne se chiffre pas juste au nombre d'appareils. Le câblage, le PoE, le NVR, les accès au bâtiment et la mise en service font bouger la vraie soumission.",
            "tags": ["Caméras de sécurité", "Soumission", "Immeuble commercial"],
            "primary_service": "security-camera-systems",
            "summary": [
                ("Budget rapide", "3 500 $ à 7 500 $ pour une petite portée, puis 8 000 $ et plus pour un système plus complet."),
                ("Ce qui fait varier le prix", "Le nombre de caméras, le câblage, le stockage, les zones extérieures et les conditions du site."),
                ("Ce qu'il faut demander", "Une soumission qui détaille les caméras, le NVR, le PoE, la rétention vidéo et les travaux de câblage."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "L'ordre de grandeur à retenir",
                    "paragraphs": [
                        "Dans un immeuble commercial, le prix d'un système de caméras n'est pas seulement le prix des appareils. Une vraie soumission inclut presque toujours le câblage, l'alimentation PoE, l'enregistrement, le montage, la configuration, les tests et la remise.",
                        "Un hall d'entrée avec quelques zones critiques ne se chiffre pas comme un immeuble avec plusieurs accès, un stationnement, des corridors, des cages d'escalier et une salle technique. Ce sont ces réalités de terrain qui expliquent l'écart entre une petite enveloppe et un vrai projet de surveillance.",
                    ],
                    "callout_label": "Réponse courte",
                    "callout": "Si vous cherchez un budget réaliste pour planifier, pensez en système complet, pas en prix par caméra.",
                },
                {
                    "eyebrow": "Budget",
                    "title": "Budgets typiques selon la portée",
                    "table": {
                        "caption": "Ordres de grandeur pour un système de caméras commercial",
                        "columns": ("Projet", "Portée typique", "Budget indicatif", "Quand ça s'applique"),
                        "rows": (
                            ("Portée simple", "4 à 6 caméras, entrée et aire commune", "3 500 $ à 7 500 $", "Petit immeuble, commerce ou bureau avec peu de zones à couvrir"),
                            ("Portée intermédiaire", "8 à 16 caméras, intérieur + extérieur", "8 000 $ à 15 000 $", "Immeuble avec plusieurs accès, stationnement ou zones sensibles"),
                            ("Portée étendue", "16 caméras et plus, stockage plus lourd", "15 000 $ à 25 000 $ +", "Site plus complexe, multi-locatif ou plusieurs secteurs à surveiller"),
                        ),
                    },
                },
                {
                    "eyebrow": "Variables",
                    "title": "Ce qui fait vraiment bouger la soumission",
                    "cards": [
                        ("Nombre de caméras", "Plus il y a de caméras, plus il faut de câblage, de ports PoE, de stockage et de temps de mise en service."),
                        ("Distances et cheminements", "Des plafonds difficiles, de longues distances, des percements ou des zones occupées font monter le temps d'installation."),
                        ("Stockage vidéo", "La rétention vidéo, la résolution et le nombre de jours d'archivage changent le NVR, les disques et le coût global."),
                        ("Zones extérieures", "Le stationnement, les entrées extérieures et les intempéries exigent souvent des boîtiers, supports et protections adaptés."),
                        ("Accès au bâtiment", "Les travaux de soir, en site occupé ou coordonnés avec des locataires demandent plus de planification."),
                        ("Intégration", "Si la surveillance doit s'aligner avec les accès, l'intercom ou le réseau existant, la portée technique augmente."),
                    ],
                },
                {
                    "eyebrow": "Préparation",
                    "title": "Ce qu'il faut avoir avant de demander un vrai prix",
                    "steps": [
                        ("Lister les zones à couvrir", "Entrées, corridors, stationnement, quai, local technique, aire commune ou périmètre."),
                        ("Indiquer le nombre d'accès et d'étages", "Le nombre de portes, de niveaux et de locaux change directement le câblage et les distances."),
                        ("Confirmer les attentes de rétention", "Combien de jours d'images voulez-vous conserver, et pour combien de caméras en même temps ?"),
                        ("Prévoir une visite du site", "Une visite permet de valider les cheminements, le local réseau, le PoE et les vraies contraintes du bâtiment."),
                    ],
                    "quote": "Une bonne soumission de caméras est détaillée, lisible et basée sur le site. Sinon, le prix de départ finit souvent par bouger.",
                },
            ],
            "faq_items": [
                ("Est-ce qu'on peut chiffrer seulement par caméra ?", "Pas de façon utile. Le prix par caméra ne couvre pas correctement le câblage, le NVR, le PoE, les supports, la main-d'oeuvre et la configuration."),
                ("Le NVR est-il toujours nécessaire ?", "Dans la plupart des projets commerciaux, oui. Il faut prévoir où les images seront enregistrées, combien de jours seront conservés et qui y aura accès."),
                ("Pourquoi deux immeubles avec le même nombre de caméras n'ont-ils pas le même prix ?", "Parce que les distances, les plafonds, les accès, les zones extérieures, le local technique et les heures de travail peuvent être complètement différents."),
                ("Quel est le meilleur moyen d'obtenir un prix fiable ?", "Envoyez le type d'immeuble, les zones à couvrir, le nombre d'étages, les accès principaux et votre échéancier. Une visite de site reste la meilleure base pour un chiffre réaliste."),
            ],
            "cta": {
                "title": "Vous voulez un prix réaliste pour votre projet de caméras ?",
                "copy": "Dites-nous le type d'immeuble, les zones à couvrir et votre échéancier. On vous revient avec une portée claire et les bons points à valider sur place.",
                "primary_label": "Obtenir une soumission",
                "primary_key": "contact",
                "secondary_label": "Voir le service caméras",
                "secondary_key": "security-camera-systems",
            },
        },
    },
    "access-control-vs-intercom": {
        "published": "2025-11-13",
        "modified": "2025-11-13",
        "author": "Yan-Erik B.",
        "reading_minutes": 4,
        "related_services": ("access-control-systems", "intercom-systems", "security-camera-systems"),
        "related_articles": ("ip-cameras-network-upgrade", "structured-cabling-foundation"),
        "fr": {
            "path": "/fr/controle-acces-vs-intercom/",
            "title": "Contrôle d'accès vs intercom | Opticable",
            "desc": "Comment choisir entre un intercom, un contrôle d'accès ou les deux pour un immeuble commercial ou multilocatif.",
            "eyebrow": "Guide de décision",
            "headline": "Contrôle d'accès vs intercom : lequel faut-il installer ?",
            "intro": "Réponse courte : un intercom sert surtout à parler avec un visiteur et à le valider à l'entrée. Un système de contrôle d'accès sert à gérer qui entre, quand et avec quels droits. Dans beaucoup d'immeubles commerciaux, les deux doivent travailler ensemble : intercom pour les visiteurs, contrôle d'accès pour les occupants, les employés et les fournisseurs autorisés.",
            "excerpt": "Un intercom et un contrôle d'accès ne règlent pas le même problème. Le bon choix dépend de qui doit entrer, comment l'entrée est gérée et quel niveau d'historique vous voulez garder.",
            "tags": ["Contrôle d'accès", "Intercom", "Entrée sécurisée"],
            "primary_service": "access-control-systems",
            "summary": [
                ("Intercom", "Idéal pour filtrer et communiquer avec les visiteurs à l'entrée."),
                ("Contrôle d'accès", "Idéal pour gérer les cartes, horaires, zones et droits d'entrée."),
                ("Les deux ensemble", "Le meilleur choix quand un immeuble doit gérer visiteurs, occupants et portes sensibles."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "Les deux outils ne servent pas au même moment",
                    "paragraphs": [
                        "Un intercom répond à la question : qui sonne et à qui parle-t-on ? Il sert à la communication et à la validation à l'entrée.",
                        "Le contrôle d'accès répond à une autre question : qui peut entrer, sur quelle porte, à quelle heure et avec quelle trace ? C'est un outil de droits, d'autorisations et de gestion continue.",
                    ],
                    "callout_label": "Décision rapide",
                    "callout": "Si vous avez seulement besoin de filtrer des visiteurs, l'intercom peut suffire. Si vous devez gérer des usagers autorisés au quotidien, il faut du contrôle d'accès. Si vous avez les deux réalités, il faut les deux.",
                },
                {
                    "eyebrow": "Comparatif",
                    "title": "Comparatif simple",
                    "table": {
                        "caption": "Intercom, contrôle d'accès ou combinaison",
                        "columns": ("Critère", "Intercom", "Contrôle d'accès", "Les deux ensemble"),
                        "rows": (
                            ("Fonction principale", "Parler avec le visiteur", "Autoriser ou refuser l'entrée", "Valider + autoriser"),
                            ("Usagers réguliers", "Limité", "Très adapté", "Très adapté"),
                            ("Visiteurs et livraisons", "Très adapté", "Partiel", "Très adapté"),
                            ("Historique des accès", "Faible ou absent", "Fort", "Fort"),
                            ("Portes sensibles", "Insuffisant seul", "Adapté", "Adapté"),
                        ),
                    },
                },
                {
                    "eyebrow": "Quand choisir",
                    "title": "Les cas les plus courants",
                    "cards": [
                        ("Intercom seul", "Petit site avec une seule entrée visiteur, peu d'usagers réguliers et sans besoin d'un historique d'accès détaillé."),
                        ("Contrôle d'accès seul", "Bureaux, locaux techniques, zones restreintes ou portes employées où les usagers sont déjà connus et autorisés."),
                        ("Intercom + accès", "Immeuble multilocatif, entrée principale, hall, livraisons, visiteurs et occupants réguliers sur la même porte ou sur le même site."),
                    ],
                },
                {
                    "eyebrow": "Choix pratique",
                    "title": "Ce qu'il faut valider avant de choisir",
                    "steps": [
                        ("Qui entre chaque jour ?", "Occupants, employés, fournisseurs, visiteurs, livreurs ou équipes de maintenance."),
                        ("Combien de portes sont concernées ?", "Une seule entrée principale n'implique pas la même architecture qu'un site avec plusieurs portes et zones sensibles."),
                        ("Avez-vous besoin d'un historique ?", "Si vous devez savoir qui est entré et quand, le contrôle d'accès devient vite indispensable."),
                        ("Faut-il voir ou parler au visiteur ?", "Si oui, l'intercom garde toute sa valeur, surtout à l'entrée principale."),
                    ],
                    "quote": "Le bon système d'entrée ne se choisit pas par habitude. Il se choisit selon les usagers, les portes et le niveau de contrôle attendu.",
                },
            ],
            "faq_items": [
                ("Est-ce qu'un intercom peut remplacer un contrôle d'accès ?", "Pas vraiment. Il peut aider à filtrer un visiteur, mais il ne gère pas bien les droits permanents, les horaires et les historiques d'accès."),
                ("Est-ce que le contrôle d'accès remplace l'intercom ?", "Pas toujours. Si vous avez des visiteurs, des livreurs ou un hall principal où il faut parler à quelqu'un avant d'ouvrir, l'intercom reste utile."),
                ("Est-ce que les deux peuvent partager la même plateforme ?", "Oui, dans plusieurs projets modernes, l'intercom, le contrôle d'accès et les caméras peuvent être gérés dans le même écosystème."),
                ("Comment savoir quoi prévoir dans la soumission ?", "Indiquez le nombre de portes, le type d'usagers, la présence de visiteurs, les horaires à gérer et les zones restreintes. C'est ce qui permet de proposer la bonne combinaison."),
            ],
            "cta": {
                "title": "Vous hésitez entre intercom et contrôle d'accès ?",
                "copy": "Décrivez votre entrée, le nombre de portes et le type d'usagers. On vous dira rapidement s'il faut un intercom, du contrôle d'accès ou une combinaison des deux.",
                "primary_label": "Parler de mon projet",
                "primary_key": "contact",
                "secondary_label": "Voir le service accès",
                "secondary_key": "access-control-systems",
            },
        },
    },
    "commercial-wifi-audit-checklist": {
        "published": "2026-01-14",
        "modified": "2026-01-14",
        "author": "Yan-Erik B.",
        "reading_minutes": 4,
        "related_services": ("commercial-wifi-installation", "structured-cabling", "network-infrastructure"),
        "related_articles": ("wifi-power", "structured-cabling-foundation"),
        "fr": {
            "path": "/fr/checklist-audit-wifi-commercial/",
            "title": "Checklist d'audit WiFi commercial | Opticable",
            "desc": "La checklist pratique pour auditer un WiFi commercial avant une nouvelle installation, une optimisation ou une demande de soumission.",
            "eyebrow": "Audit WiFi",
            "headline": "Checklist d'audit WiFi commercial : quoi vérifier avant de demander une soumission",
            "intro": "Réponse courte : avant de changer des points d'accès WiFi ou d'augmenter le budget, il faut vérifier la couverture, la densité d'usagers, le câblage, les zones mortes, les interférences, les usages réels et les limites du local réseau. Un bon audit WiFi évite de remplacer du matériel alors que le vrai problème est dans le positionnement, le PoE, le câblage ou la planification radio.",
            "excerpt": "Un audit WiFi commercial utile regarde le site, les usages, les interférences, le câblage et le réseau. Sans ça, on change souvent le mauvais élément.",
            "tags": ["WiFi commercial", "Audit réseau", "Soumission"],
            "primary_service": "commercial-wifi-installation",
            "summary": [
                ("Avant de remplacer", "Vérifier la couverture, les usages, le câblage et les sources d'interférence."),
                ("Ce qui manque souvent", "Un plan du site clair, la liste des zones critiques et la validation du PoE."),
                ("Le vrai gain", "Une soumission plus juste et un déploiement qui vise le vrai problème."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "Ce qu'un bon audit doit confirmer",
                    "paragraphs": [
                        "Le WiFi ne se limite pas au modèle de point d'accès. Il dépend aussi du câblage, du PoE disponible, des matériaux du bâtiment, du nombre d'usagers, des applications critiques et des réseaux voisins.",
                        "L'audit sert à transformer des plaintes vagues comme ça coupe ou c'est lent en causes techniques concrètes. C'est seulement à partir de là qu'une soumission devient utile.",
                    ],
                    "callout_label": "À retenir",
                    "callout": "Si personne ne valide le site, les zones critiques et le câblage, la solution proposée risque de corriger le symptôme au lieu de la cause.",
                },
                {
                    "eyebrow": "Checklist",
                    "title": "Checklist à utiliser avant une soumission",
                    "table": {
                        "caption": "Points à vérifier avant un projet WiFi commercial",
                        "columns": ("Élément", "Pourquoi", "Signal d'alerte"),
                        "rows": (
                            ("Plan du site", "Savoir où placer les points d'accès et quelles zones couvrir", "Aucun plan, aucune notion des zones critiques"),
                            ("Nombre d'usagers", "Dimensionner la densité et la bande passante", "Le site est pensé comme une petite installation résidentielle"),
                            ("Câblage et PoE", "Valider que chaque point d'accès peut être alimenté et relié proprement", "Câbles inconnus, longueurs non confirmées, commutateurs limités"),
                            ("Interférences", "Identifier les réseaux voisins et les zones bruyantes", "Bureaux denses, immeuble occupé, équipements 2.4 GHz partout"),
                            ("Usages critiques", "Prioriser caisse, téléphonie, visio, terminaux, IoT ou invités", "Tout le trafic est mis dans le même panier"),
                        ),
                    },
                },
                {
                    "eyebrow": "Sur le terrain",
                    "title": "Ce qu'on valide pendant la visite",
                    "cards": [
                        ("Zones mortes", "Escaliers, corridors, salles de réunion, entrepôts, terrasses, quais ou aires communes qui perdent le signal."),
                        ("Matériaux du bâtiment", "Béton, métal, vitrages traités et plafonds techniques changent la propagation radio."),
                        ("Local réseau", "État du rack, budget PoE, commutateurs, étiquetage et marge disponible pour ajouter des points d'accès."),
                        ("Usages réels", "Visioconférence, paiements, invités, IoT, caméras ou postes fixes qui partagent le même environnement sans fil."),
                    ],
                },
                {
                    "eyebrow": "Préparation",
                    "title": "Comment arriver prêt pour l'audit",
                    "steps": [
                        ("Identifier les plaintes précises", "Où ça coupe, à quelles heures et avec quels appareils."),
                        ("Lister les usages critiques", "Paiement, voix, visio, invités, WiFi partagé, IoT ou opérations de site."),
                        ("Prévoir l'accès aux salles techniques", "Sans accès au rack, aux commutateurs et aux alimentations, l'audit reste incomplet."),
                        ("Nommer les zones prioritaires", "Les entrées, salles de réunion, caisses, corridors ou aires communes n'ont pas toutes la même priorité."),
                    ],
                    "quote": "Un audit WiFi sérieux permet d'acheter moins au hasard et d'installer plus juste.",
                },
            ],
            "faq_items": [
                ("Faut-il toujours faire un audit avant de changer les points d'accès ?", "Pas obligatoirement complet, mais il faut au minimum vérifier le site, les zones critiques, le câblage et les interférences. Sinon on change souvent le mauvais élément."),
                ("Pourquoi le câblage compte-t-il autant pour le WiFi ?", "Parce qu'un point d'accès WiFi dépend d'un lien réseau stable et d'un PoE adéquat. Si la base filaire est faible, le point d'accès ne performera jamais comme prévu."),
                ("Quelles informations accélèrent une soumission WiFi ?", "La superficie, le type d'immeuble, le nombre d'usagers, les zones problématiques, les usages critiques et l'état du local réseau."),
                ("Peut-on corriger un WiFi lent sans tout remplacer ?", "Oui, souvent. Une réorganisation des canaux, du positionnement, du PoE ou du câblage peut régler une grande partie du problème sans repartir de zéro."),
            ],
            "cta": {
                "title": "Votre WiFi mérite un vrai diagnostic ?",
                "copy": "Expliquez-nous où le réseau décroche, combien d'usagers il sert et quel type de bâtiment vous exploitez. On vous dira quoi vérifier et comment cadrer la suite.",
                "primary_label": "Demander une évaluation",
                "primary_key": "contact",
                "secondary_label": "Voir le service WiFi",
                "secondary_key": "commercial-wifi-installation",
            },
        },
    },
    "cat6a-or-fiber-commercial-building": {
        "published": "2026-02-11",
        "modified": "2026-02-11",
        "author": "L'équipe Opticable",
        "reading_minutes": 4,
        "related_services": ("structured-cabling", "fiber-optic-installation", "network-infrastructure"),
        "related_articles": ("structured-cabling-foundation", "wifi-power"),
        "fr": {
            "path": "/fr/cat6a-ou-fibre-pour-immeuble-commercial/",
            "title": "Cat6A ou fibre pour immeuble commercial | Opticable",
            "desc": "Quand choisir du Cat6A, quand choisir de la fibre et pourquoi la plupart des immeubles commerciaux ont besoin des deux.",
            "eyebrow": "Câblage commercial",
            "headline": "Cat6A ou fibre pour un immeuble commercial : que faut-il choisir ?",
            "intro": "Réponse courte : le Cat6A sert surtout à relier les appareils finaux et à transporter le PoE vers les points d'accès WiFi, les caméras et les lecteurs. La fibre sert surtout aux longues distances, aux liens entre étages et aux liaisons entre le local réseau principal, les petits locaux d'étage ou les bâtiments voisins. Dans beaucoup d'immeubles commerciaux, la bonne réponse n'est pas l'un ou l'autre : c'est une base fibre avec des dessertes Cat6A.",
            "excerpt": "Le Cat6A et la fibre ne jouent pas le même rôle. Le bon choix dépend de la distance, du débit, du PoE et de la structure du bâtiment.",
            "tags": ["Cat6A", "Fibre optique", "Câblage structuré"],
            "primary_service": "structured-cabling",
            "summary": [
                ("Cat6A", "Pour les postes, le WiFi, les caméras, la téléphonie IP et le PoE dans un étage ou une zone."),
                ("Fibre", "Pour les backbones, les colonnes montantes, les longues distances et les liaisons critiques."),
                ("La vraie architecture", "Souvent un backbone fibre alimente des étages ou des locaux, puis le Cat6A dessert les équipements finaux."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "Les deux médias n'ont pas le même rôle",
                    "paragraphs": [
                        "Le Cat6A est excellent pour les postes, les points d'accès WiFi, les caméras IP, les lecteurs et les appareils qui ont besoin de données et souvent de PoE. Il reste très pratique quand les distances sont maîtrisées et que le média arrive directement jusqu'à l'équipement.",
                        "La fibre devient la bonne réponse quand il faut traverser plusieurs étages, de longues distances, des environnements plus sensibles aux perturbations ou quand on veut donner plus de marge au backbone du bâtiment.",
                    ],
                    "callout_label": "Règle rapide",
                    "callout": "Cat6A pour desservir les appareils. Fibre pour relier les salles réseau, les étages et les longues distances.",
                },
                {
                    "eyebrow": "Comparatif",
                    "title": "Comparatif rapide",
                    "table": {
                        "caption": "Cat6A vs fibre en contexte commercial",
                        "columns": ("Critère", "Cat6A", "Fibre"),
                        "rows": (
                            ("PoE", "Oui", "Non"),
                            ("Distance utile", "Jusqu'à environ 90 m par lien horizontal", "Bien au-delà pour backbone et interconnexions"),
                            ("Appareils finaux", "Très adapté", "Peu adapté directement"),
                            ("Backbone entre étages", "Possible mais vite limité", "Très adapté"),
                            ("Sensibilité électromagnétique", "Plus sensible", "Très faible"),
                        ),
                    },
                },
                {
                    "eyebrow": "Cas concrets",
                    "title": "Quand choisir quoi",
                    "cards": [
                        ("Cat6A", "Postes de travail, points d'accès WiFi, caméras, téléphonie IP et lecteurs d'accès dans un étage ou une zone."),
                        ("Fibre", "Lien entre le local réseau principal, un local d'étage, un autre niveau ou un bâtiment voisin."),
                        ("Les deux", "Immeuble multi-étages ou multi-zones où chaque local réseau distribue ensuite du Cat6A vers les appareils."),
                    ],
                },
                {
                    "eyebrow": "Décision",
                    "title": "Les questions qui tranchent",
                    "steps": [
                        ("Faut-il du PoE ?", "Si oui, le Cat6A est généralement requis jusqu'à l'équipement final."),
                        ("Quelle distance faut-il couvrir ?", "Quand on dépasse facilement la logique horizontale d'un étage, la fibre prend vite l'avantage."),
                        ("S'agit-il d'un backbone ou d'une desserte finale ?", "Le backbone appelle souvent la fibre, la desserte finale appelle souvent le Cat6A."),
                        ("Faut-il préparer la croissance du bâtiment ?", "Un backbone fibre bien placé donne plus de marge pour les expansions futures."),
                    ],
                    "quote": "Le bon choix de média dépend du rôle du lien. Un mauvais choix de rôle coûte souvent plus cher à corriger plus tard qu'à bien planifier maintenant.",
                },
            ],
            "faq_items": [
                ("Peut-on tout faire en Cat6A ?", "Pas idéalement. Pour les courts liens finaux oui, mais pour les backbones, les grandes distances et les colonnes montantes, la fibre devient souvent la meilleure base."),
                ("Peut-on alimenter un point d'accès WiFi ou une caméra directement sur fibre ?", "Non, pas comme avec du PoE sur cuivre. Il faut ensuite une conversion ou un équipement intermédiaire. C'est pourquoi le Cat6A reste central pour les appareils finaux."),
                ("Est-ce que la fibre est toujours plus chère ?", "Pas toujours si on parle d'un backbone stratégique. Elle peut éviter des limites futures et simplifier certaines longues liaisons. La bonne comparaison se fait sur l'architecture complète."),
                ("Que faut-il envoyer pour bien cadrer la soumission ?", "Le nombre d'étages, la distance entre locaux réseau, les appareils à alimenter en PoE, la présence de locaux techniques existants et les zones à desservir."),
            ],
            "cta": {
                "title": "Vous devez choisir entre Cat6A, fibre ou les deux ?",
                "copy": "Décrivez le bâtiment, le nombre d'étages, les locaux réseau et les équipements à desservir. On vous dira quelle architecture a du sens avant de tirer le moindre câble.",
                "primary_label": "Obtenir un avis",
                "primary_key": "contact",
                "secondary_label": "Voir le service câblage",
                "secondary_key": "structured-cabling",
            },
        },
    },
    "technology-retrofit-occupied-building": {
        "published": "2026-03-06",
        "modified": "2026-03-06",
        "author": "Yan-Erik B.",
        "reading_minutes": 4,
        "related_services": ("structured-cabling", "access-control-systems", "commercial-wifi-installation"),
        "related_articles": ("structured-cabling-foundation", "ip-cameras-network-upgrade"),
        "fr": {
            "path": "/fr/mise-a-niveau-technologique-immeuble-occupe/",
            "title": "Mise à niveau technologique dans un immeuble occupé | Opticable",
            "desc": "Comment planifier une mise à niveau technologique dans un immeuble commercial ou multilocatif occupé sans nuire aux opérations.",
            "eyebrow": "Projet en site occupé",
            "headline": "Comment planifier une mise à niveau technologique dans un immeuble occupé",
            "intro": "Réponse courte : une mise à niveau technologique en immeuble occupé se planifie par phases, avec une visite de site sérieuse, des fenêtres d'intervention claires, un plan de communication et des cheminements validés avant le départ. Ce qui crée les retards n'est pas le matériel : ce sont les accès, les heures permises, les occupants, les plafonds fermés et l'absence de séquence claire entre les corps de métier.",
            "excerpt": "Dans un immeuble occupé, une bonne mise à niveau est surtout une question de phasage, d'accès, de coordination et de cheminements validés avant le premier percement.",
            "tags": ["Mise à niveau", "Immeuble occupé", "Coordination de projet"],
            "primary_service": "structured-cabling",
            "summary": [
                ("Le vrai enjeu", "Le phasage et la coordination comptent autant que le choix des systèmes."),
                ("Ce qui évite les surprises", "Visite de site, accès validés, fenêtres de travail et séquence claire."),
                ("Le bon résultat", "Un projet livré sans bloquer inutilement les usagers et sans refaire deux fois le même travail."),
            ],
            "sections": [
                {
                    "eyebrow": "Réponse directe",
                    "title": "Pourquoi les projets en site occupé dérapent",
                    "paragraphs": [
                        "Dans un immeuble en exploitation, chaque intervention touche autre chose : accès, locataires, horaires, bruit, sécurité, entretien, ascenseurs, plafonds, salles techniques et parfois plusieurs fournisseurs déjà en place.",
                        "Sans séquence claire, on finit par revenir sur place, ouvrir deux fois le même secteur, déplacer des interventions et rallonger le chantier. Une bonne mise à niveau commence donc par la logistique du site, pas par la liste de matériel.",
                    ],
                    "callout_label": "Point critique",
                    "callout": "Le succès d'une mise à niveau en immeuble occupé repose sur la séquence du travail autant que sur la qualité technique de l'installation.",
                },
                {
                    "eyebrow": "Phases",
                    "title": "Séquence recommandée",
                    "table": {
                        "caption": "Une séquence de mise à niveau qui limite les reprises",
                        "columns": ("Phase", "Objectif", "Résultat attendu"),
                        "rows": (
                            ("Relevé du site", "Valider accès, cheminements, locaux et contraintes d'occupation", "Une portée réelle et pas théorique"),
                            ("Phasage", "Découper par zones, étages ou périodes d'intervention", "Moins d'impact sur les occupants"),
                            ("Installation", "Exécuter les travaux de câblage, d'équipement et de configuration dans le bon ordre", "Moins de retours en arrière"),
                            ("Remise", "Tester, documenter et remettre zone par zone", "Un site exploitable tout au long du projet"),
                        ),
                    },
                },
                {
                    "eyebrow": "Ce qu'il faut cadrer",
                    "title": "Les points à verrouiller avant le départ",
                    "cards": [
                        ("Accès", "Qui ouvre les locaux, les plafonds, les salles techniques et à quelles heures."),
                        ("Fenêtres de travail", "Travaux de jour, de soir, de fin de semaine ou zone par zone selon les usages du bâtiment."),
                        ("Communication", "Qui doit être avisé avant les interventions, les coupures ou les accès temporaires modifiés."),
                        ("Coordination", "Comment le projet s'aligne avec l'électricien, l'entrepreneur général, l'entretien ou les équipes de sécurité déjà en place."),
                        ("Cheminements", "Quels passages sont valides, quels plafonds ou colonnes sont disponibles et ce qui est interdit."),
                        ("Remise", "Quel niveau de test, d'étiquetage et de documentation est attendu à chaque phase."),
                    ],
                },
                {
                    "eyebrow": "Préparation",
                    "title": "Comment accélérer une demande de soumission",
                    "steps": [
                        ("Donner le type d'immeuble et son occupation", "Bureaux, multilocatif, commerce, site mixte ou portefeuille géré."),
                        ("Nommer les systèmes visés", "Caméras, contrôle d'accès, intercom, WiFi, câblage, backbone ou mise à niveau réseau."),
                        ("Indiquer les contraintes", "Horaires permis, zones sensibles, exigences de sécurité, bruit ou accès limités."),
                        ("Dire comment vous voulez phaser", "Par étage, par entrée, par aile, par lots ou par fenêtres hors heures."),
                    ],
                    "quote": "En site occupé, la meilleure soumission est celle qui explique aussi comment le projet va se dérouler, pas seulement ce qui sera installé.",
                },
            ],
            "faq_items": [
                ("Peut-on faire ce type de projet sans fermer le bâtiment ?", "Oui, souvent, mais il faut planifier les zones, les horaires et les accès avec précision. C'est justement le coeur d'une mise à niveau en site occupé."),
                ("Pourquoi faut-il presque toujours une visite de site ?", "Parce que les cheminements, les plafonds, les locaux techniques, les accès et les contraintes d'occupation ne se lisent pas bien sur une simple description par courriel."),
                ("Est-ce qu'on peut phaser le projet ?", "Oui. C'est souvent la meilleure approche : par étage, par entrée, par zone ou par fenêtre de travail pour limiter l'impact sur les occupants."),
                ("Qu'est-ce qui aide le plus à obtenir une bonne soumission ?", "Le type d'immeuble, l'occupation, les systèmes visés, les contraintes horaires, les zones sensibles et la façon dont vous voulez phaser l'intervention."),
            ],
            "cta": {
                "title": "Vous planifiez une mise à niveau dans un immeuble déjà occupé ?",
                "copy": "Parlez-nous du bâtiment, des systèmes à moderniser et des contraintes d'occupation. On vous aidera à cadrer la séquence avant de lancer les travaux.",
                "primary_label": "Planifier mon projet",
                "primary_key": "contact",
                "secondary_label": "Voir le service câblage",
                "secondary_key": "structured-cabling",
            },
        },
    },
}

from english_resource_pages import EN_GUIDE_ARTICLES

for _key, _article in EN_GUIDE_ARTICLES.items():
    GUIDE_ARTICLES.setdefault(_key, {}).update({"en": _article})
