INDUSTRY_DETAIL_PAGES = {
    "industry-office-building": {
        "path": "/fr/clientele/immeuble-de-bureaux/",
        "title": "Systèmes technologiques pour immeubles de bureaux | Opticable",
        "desc": "Caméras, contrôle d'accès, WiFi, câblage et infrastructure réseau pour immeubles de bureaux et espaces professionnels.",
        "eyebrow": "Clientèle",
        "headline": "Technologie pour immeubles de bureaux",
        "intro": "Dans un immeuble de bureaux, les systèmes doivent rester simples à exploiter, faciles à faire évoluer et compatibles avec un bâtiment occupé. Les besoins tournent souvent autour des entrées, du WiFi, des salles de réunion, des locaux techniques et de la remise en ordre du réseau.",
        "panel_title": "Ce qu'on voit le plus souvent",
        "panel_copy": "Entrées à sécuriser, salles techniques à mieux contrôler, couverture WiFi inégale, local réseau à remettre propre et nouveaux postes à raccorder.",
        "service_keys": ("access-control-systems", "commercial-wifi-installation", "security-camera-systems", "structured-cabling"),
        "guide_keys": ("access-control-pricing-commercial-building", "structured-cabling-pricing-office-retail", "network-room-rack-cleanup"),
        "sections": [
            {
                "eyebrow": "Systèmes fréquents",
                "title": "Ce qu'on installe le plus souvent",
                "items": [
                    "Contrôle d'accès sur l'entrée principale, les salles de serveurs et les zones restreintes",
                    "Caméras aux entrées, dans les corridors, les quais et les zones sensibles",
                    "WiFi commercial pour bureaux, salles de réunion et aires communes",
                    "Ajout de prises réseau pour postes, téléphonie IP, bornes et équipements",
                    "Remise en ordre du rack et du local réseau avant une expansion",
                ],
            },
            {
                "eyebrow": "Contraintes",
                "title": "Les contraintes typiques d'un immeuble de bureaux",
                "cards": [
                    ("Bâtiment occupé", "Les travaux doivent souvent se faire sans nuire aux occupants ni aux opérations."),
                    ("Accès par étages", "Les parcours, les plafonds et les locaux techniques changent d'un étage à l'autre."),
                    ("Équipes mixtes", "Gestionnaire, TI, direction et occupants n'ont pas tous les mêmes priorités."),
                    ("Évolution continue", "Le site change au rythme des déménagements, des agrandissements et des réaménagements."),
                ],
            },
            {
                "eyebrow": "Projets fréquents",
                "title": "Portées qu'on voit souvent",
                "items": [
                    "Sécuriser l'entrée principale et la salle de serveurs",
                    "Améliorer le WiFi dans les salles de réunion et les zones plus denses",
                    "Ajouter des caméras au stationnement, aux accès et aux couloirs",
                    "Augmenter le nombre de prises réseau pour de nouveaux postes",
                    "Reprendre un local réseau devenu trop désorganisé",
                    "Préparer un étage ou une suite pour un nouveau locataire",
                ],
            },
            {
                "eyebrow": "Déroulement",
                "title": "Comment on intervient dans ce type de site",
                "paragraphs": [
                    "On commence par lire le bâtiment comme un environnement en service : chemins, accès, heures possibles, zones sensibles et état du local réseau.",
                    "Ensuite, on cadre la portée la plus utile pour l'exploitation réelle du site, pas juste une liste d'équipements. Le but est de livrer un système plus clair à gérer et plus simple à faire évoluer.",
                ],
            },
        ],
        "faq_items": [
            ("Travaillez-vous dans des bureaux en activité ?", "Oui. C'est une réalité fréquente et la planification se fait en fonction des heures possibles et des zones sensibles."),
            ("Est-ce que vous pouvez prendre seulement une partie du site ?", "Oui. On peut intervenir sur une entrée, un étage, une salle technique ou une portée plus complète."),
            ("Est-ce que vous faites aussi la remise en ordre du local réseau ?", "Oui. C'est souvent une étape clé avant l'ajout d'autres systèmes."),
            ("Comment bien demander une soumission ?", "Indiquez le nombre d'étages, les zones visées, les systèmes concernés et les contraintes d'accès."),
        ],
        "cta_title": "Vous gérez un immeuble de bureaux ?",
        "cta_copy": "Décrivez les zones à traiter, les systèmes visés et les contraintes du site. On vous revient avec la bonne prochaine étape.",
        "cta_label": "Obtenir une soumission",
    },
    "industry-multi-tenant-building": {
        "path": "/fr/clientele/immeuble-multilocatif/",
        "title": "Systèmes technologiques pour immeubles multilocatifs | Opticable",
        "desc": "Intercom, contrôle d'accès, caméras, WiFi d'aires communes et câblage pour immeubles multilocatifs.",
        "eyebrow": "Clientèle",
        "headline": "Technologie pour immeubles multilocatifs",
        "intro": "Dans un immeuble multilocatif, les priorités tournent presque toujours autour de l'entrée, des visiteurs, des aires communes, du stationnement et de la gestion à distance. Les systèmes doivent rester clairs pour le gestionnaire sans compliquer la vie des occupants.",
        "panel_title": "Les besoins qui reviennent le plus",
        "panel_copy": "Intercom ou intercom vidéo, contrôle d'accès pour les entrées, caméras dans les aires communes, WiFi partagé et logique simple pour la gestion du bâtiment.",
        "service_keys": ("intercom-systems", "access-control-systems", "security-camera-systems", "commercial-wifi-installation"),
        "guide_keys": ("intercom-pricing-multi-tenant-building", "intercom-audio-or-video-commercial-building", "access-control-pricing-commercial-building"),
        "sections": [
            {
                "eyebrow": "Systèmes fréquents",
                "title": "Ce qu'on voit le plus souvent",
                "items": [
                    "Intercom ou intercom vidéo à l'entrée principale",
                    "Contrôle d'accès sur les entrées, le stationnement ou les locaux communs",
                    "Caméras dans le hall, les corridors, les escaliers et le stationnement",
                    "WiFi dans les aires communes ou pour les services du bâtiment",
                    "Câblage et remise en ordre du local réseau",
                ],
            },
            {
                "eyebrow": "Contraintes",
                "title": "Les contraintes propres à ce type d'immeuble",
                "cards": [
                    ("Bâtiment occupé", "Les travaux doivent s'intégrer à la vie quotidienne des résidents."),
                    ("Entrées partagées", "Il faut bien gérer visiteurs, occupants, fournisseurs et entretien."),
                    ("Gestion à distance", "Le gestionnaire veut souvent voir, ouvrir ou vérifier sans se déplacer."),
                    ("Espaces communs", "Les halls, corridors, stationnements et buanderies demandent chacun une logique différente."),
                ],
            },
            {
                "eyebrow": "Projets fréquents",
                "title": "Portées qui reviennent souvent",
                "items": [
                    "Remplacer un vieux panneau d'intercom devenu peu fiable",
                    "Ajouter un contrôle d'accès sur l'entrée principale et le garage",
                    "Installer des caméras dans le hall, les couloirs et le stationnement",
                    "Ajouter du WiFi dans les corridors ou la salle commune",
                    "Mieux encadrer les accès aux locaux techniques",
                    "Moderniser un système ancien sans refaire tout l'immeuble d'un coup",
                ],
            },
            {
                "eyebrow": "Approche",
                "title": "Comment on cadre le projet",
                "paragraphs": [
                    "On regarde d'abord la logique d'entrée du bâtiment : qui doit entrer, comment les visiteurs sont validés et où les zones sensibles commencent vraiment.",
                    "Ensuite, on aligne l'intercom, l'accès, les caméras et le réseau pour que la gestion reste simple au quotidien et pas seulement à la livraison.",
                ],
            },
        ],
        "faq_items": [
            ("Intervenez-vous seulement sur l'entrée principale ?", "Oui, on peut faire une intervention ciblée sur une seule entrée ou sur une portée plus large."),
            ("Est-ce que l'intercom et le contrôle d'accès peuvent fonctionner ensemble ?", "Oui, et c'est souvent la meilleure logique pour un immeuble multilocatif."),
            ("Travaillez-vous dans les aires communes occupées ?", "Oui. Les travaux sont planifiés pour limiter les interruptions."),
            ("Comment demander une soumission utile ?", "Indiquez le nombre d'entrées, le type d'immeuble, les systèmes visés et ce qui pose problème aujourd'hui."),
        ],
        "cta_title": "Vous gérez un immeuble multilocatif ?",
        "cta_copy": "Décrivez le type d'entrée, les systèmes visés et les zones communes à traiter. On vous dira quelle portée prévoir.",
        "cta_label": "Obtenir une soumission",
    },
    "industry-retail-and-sales-floor": {
        "path": "/fr/clientele/commerce-et-vente-au-detail/",
        "title": "Systèmes technologiques pour commerces et vente au détail | Opticable",
        "desc": "Caméras, WiFi, contrôle d'accès et câblage pour commerces, boutiques et espaces de vente.",
        "eyebrow": "Clientèle",
        "headline": "Technologie pour commerces et espaces de vente",
        "intro": "Dans un commerce, les systèmes doivent soutenir l'opération avant tout : caisse, arrière-boutique, réception de marchandise, WiFi stable et sécurité claire. Les travaux doivent souvent se faire rapidement et en dehors des heures de pointe.",
        "panel_title": "Les priorités typiques",
        "panel_copy": "Caméras à la caisse et aux entrées, WiFi stable pour l'opération, accès contrôlé aux zones arrière et câblage propre pour le point de vente.",
        "service_keys": ("security-camera-systems", "commercial-wifi-installation", "access-control-systems", "structured-cabling"),
        "guide_keys": ("analog-cctv-to-ip-migration", "structured-cabling-pricing-office-retail", "commercial-wifi-audit-checklist"),
        "sections": [
            {
                "eyebrow": "Systèmes fréquents",
                "title": "Ce qu'on installe le plus souvent",
                "items": [
                    "Caméras sur les entrées, la caisse, l'aire de vente et l'arrière-boutique",
                    "WiFi commercial pour terminaux, employés et zones invitées si nécessaire",
                    "Contrôle d'accès sur l'entrepôt, le bureau ou la porte arrière",
                    "Prises réseau pour caisse, postes de travail et équipements d'opération",
                    "Remise en ordre du rack ou du petit local réseau",
                ],
            },
            {
                "eyebrow": "Contraintes",
                "title": "Ce qui change la façon d'intervenir",
                "cards": [
                    ("Heures d'ouverture", "Le commerce doit souvent rester fonctionnel pendant les travaux."),
                    ("Zones critiques", "La caisse, le POS, l'arrière-boutique et la réception demandent une attention particulière."),
                    ("WiFi opérationnel", "Un réseau instable bloque vite les paiements et les opérations quotidiennes."),
                    ("Petits espaces", "Le site est parfois compact, mais chargé en équipements et en circulation."),
                ],
            },
            {
                "eyebrow": "Projets fréquents",
                "title": "Portées qu'on voit souvent",
                "items": [
                    "Ajouter des caméras à la caisse, aux entrées et au stationnement",
                    "Reprendre un WiFi instable pour les terminaux et les employés",
                    "Sécuriser l'arrière-boutique ou l'entrepôt",
                    "Ajouter des prises réseau pour de nouveaux équipements",
                    "Migrer un vieux système de surveillance vers IP",
                    "Remettre propre un rack devenu trop improvisé",
                ],
            },
            {
                "eyebrow": "Approche",
                "title": "Comment on cadre ce type de site",
                "paragraphs": [
                    "On priorise d'abord les zones qui touchent directement l'opération : caisse, WiFi, arrière-boutique, livraison et accès du personnel.",
                    "Le but est de livrer quelque chose de fiable et simple à soutenir, sans alourdir inutilement l'environnement ni les opérations.",
                ],
            },
        ],
        "faq_items": [
            ("Travaillez-vous en dehors des heures d'ouverture ?", "Oui, quand le site l'exige, on planifie en fonction des contraintes d'opération."),
            ("Pouvez-vous intervenir sur un seul besoin comme le WiFi ou les caméras ?", "Oui. On peut prendre une portée très ciblée ou une portée plus complète."),
            ("Est-ce que vous séparez les réseaux si nécessaire ?", "Oui, selon les besoins du site et des équipements d'opération."),
            ("Que faut-il vous envoyer pour une soumission ?", "Le type de commerce, les zones visées, les systèmes concernés et les contraintes d'horaire."),
        ],
        "cta_title": "Vous exploitez un commerce ou un point de vente ?",
        "cta_copy": "Décrivez la zone de vente, l'arrière-boutique et les systèmes à corriger. On vous aide à cadrer la bonne portée.",
        "cta_label": "Obtenir une soumission",
    },
    "industry-warehouse-and-industrial": {
        "path": "/fr/clientele/entrepot-et-industriel/",
        "title": "Systèmes technologiques pour entrepôts et sites industriels | Opticable",
        "desc": "Caméras, contrôle d'accès, WiFi, fibre et infrastructure réseau pour entrepôts et sites industriels légers.",
        "eyebrow": "Clientèle",
        "headline": "Technologie pour entrepôts et sites industriels",
        "intro": "Dans un entrepôt ou un site industriel léger, les besoins tournent souvent autour du périmètre, des quais, des zones restreintes, du WiFi opérationnel et des liens réseau plus robustes entre les espaces. Les conditions du site dictent fortement la portée technique.",
        "panel_title": "Ce qui revient le plus",
        "panel_copy": "Caméras au périmètre et aux quais, accès contrôlé aux zones sensibles, WiFi pour les opérations et backbone plus solide entre les zones techniques.",
        "service_keys": ("security-camera-systems", "access-control-systems", "commercial-wifi-installation", "fiber-optic-installation"),
        "guide_keys": ("analog-cctv-to-ip-migration", "commercial-wifi-audit-checklist", "cat6a-or-fiber-commercial-building"),
        "sections": [
            {
                "eyebrow": "Systèmes fréquents",
                "title": "Ce qu'on met le plus souvent en place",
                "items": [
                    "Caméras sur le périmètre, les quais, les portes et les zones de circulation",
                    "Contrôle d'accès sur les bureaux, les salles électriques, les locaux techniques et les accès sensibles",
                    "WiFi commercial pour les opérations, les quais ou les espaces à couverture difficile",
                    "Liaisons réseau ou fibre entre les zones techniques, les bureaux et les espaces plus éloignés",
                    "Remise en ordre du rack et de l'infrastructure réseau",
                ],
            },
            {
                "eyebrow": "Contraintes",
                "title": "Les réalités du terrain",
                "cards": [
                    ("Distances", "Les liens sont souvent plus longs et les zones plus étendues que dans un bureau classique."),
                    ("Matériaux", "Métal, béton, hauteur et structures ouvertes changent la couverture et les parcours."),
                    ("Sécurité opérationnelle", "Les zones sensibles, l'inventaire et les quais demandent une logique claire."),
                    ("Continuité", "Le site reste souvent en activité pendant les travaux et ne se prête pas à l'improvisation."),
                ],
            },
            {
                "eyebrow": "Projets fréquents",
                "title": "Portées qu'on voit souvent",
                "items": [
                    "Ajouter des caméras sur les quais, les portes et le stationnement",
                    "Sécuriser des zones techniques ou des zones d'accès limité",
                    "Améliorer un WiFi trop faible dans les espaces de travail plus étendus",
                    "Ajouter une liaison en fibre ou en Cat6A entre deux zones du site",
                    "Moderniser un vieux système de surveillance ou d'accès",
                    "Reprendre un local réseau devenu trop chargé ou mal documenté",
                ],
            },
            {
                "eyebrow": "Approche",
                "title": "Comment on planifie ce type de projet",
                "paragraphs": [
                    "On commence par identifier les zones critiques, les distances, les chemins possibles et l'état réel de la base réseau.",
                    "Ensuite, on choisit la bonne combinaison de caméras, d'accès, de WiFi et de liaisons pour que l'installation reste robuste et utile sur le terrain.",
                ],
            },
        ],
        "faq_items": [
            ("Est-ce que vous faites seulement des bureaux et commerces ?", "Non. On intervient aussi sur des entrepôts et des sites industriels légers quand la portée correspond à nos services."),
            ("Quand faut-il prévoir de la fibre ?", "Quand les distances, les capacités ou la structure du site rendent le cuivre moins logique."),
            ("Le WiFi en entrepôt est-il très différent ?", "Oui, souvent. La hauteur, le métal, les interférences et les déplacements changent la façon de le planifier."),
            ("Que faut-il envoyer pour bien cadrer la demande ?", "Le type de site, les zones à traiter, les distances approximatives et les systèmes visés."),
        ],
        "cta_title": "Vous exploitez un entrepôt ou un site industriel ?",
        "cta_copy": "Décrivez les zones à sécuriser, à couvrir ou à relier. On vous aide à cadrer une portée réaliste pour le site.",
        "cta_label": "Obtenir une soumission",
    },
}
