CAMPAIGN_LANDING_PAGES = {
    "lp-commercial-door-access": {
        "path": "/fr/lp/controle-acces-porte-commerciale/",
        "title": "Contrôle d'accès pour porte commerciale | Opticable",
        "desc": "Demandez une soumission pour le contrôle d'accès d'une porte commerciale, d'un hall ou d'une zone restreinte.",
        "eyebrow": "Contrôle d'accès",
        "headline": "Contrôle d'accès pour porte commerciale, hall et zone restreinte",
        "intro": "Vous voulez sécuriser une porte commerciale ou mieux gérer qui entre, quand et où ? On installe des systèmes de contrôle d'accès pour entrées principales, portes arrière, halls et locaux sensibles.",
        "panel_title": "Ce qu'on prend en charge",
        "panel_copy": "Lecteurs, quincaillerie, câblage, panneau de contrôle, mise en service et logique d'accès adaptée au site.",
        "items": [
            "Porte arrière ou porte de personnel",
            "Entrée principale et hall commercial",
            "Salle technique ou zone restreinte",
            "Petite portée ou projet multi-portes",
        ],
        "benefits": [
            ("Portée claire", "On cadre la vraie portée selon les portes et les contraintes du site."),
            ("Installation propre", "Câblage, quincaillerie et mise en service sont intégrés dans une seule portée."),
            ("Plus simple à gérer", "Les accès sont plus clairs à administrer ensuite."),
        ],
        "cta_title": "Parlez-nous de vos portes et de votre bâtiment",
        "cta_copy": "Dites-nous combien de portes sont visées, le type d'immeuble et les contraintes du site. On vous reviendra avec la bonne prochaine étape.",
        "cta_label": "Obtenir une soumission",
        "service_key": "access-control-systems",
    },
    "lp-multitenant-intercom": {
        "path": "/fr/lp/intercom-immeuble-multilogement/",
        "title": "Intercom pour immeuble multilogement | Opticable",
        "desc": "Soumission pour intercom audio ou vidéo dans un immeuble multilogement, avec ouverture de porte et logique visiteurs.",
        "eyebrow": "Intercom",
        "headline": "Intercom audio ou vidéo pour immeuble multilogement",
        "intro": "Vous voulez moderniser l'entrée d'un immeuble multilogement ? On installe des intercoms pensés pour les visiteurs, les entrées principales, les aires communes et la gestion à distance du bâtiment.",
        "panel_title": "Portées fréquentes",
        "panel_copy": "Remplacement d'un vieux panneau, ajout d'un intercom vidéo ou intégration avec l'ouverture de porte et le contrôle d'accès.",
        "items": [
            "Entrée principale de l'immeuble",
            "Intercom audio ou vidéo",
            "Ouverture de porte et logique visiteurs",
            "Coordination avec l'accès si nécessaire",
        ],
        "benefits": [
            ("Meilleure validation", "On choisit la bonne logique entre audio simple, vidéo ou intégration plus complète."),
            ("Entrée plus claire", "La communication et l'ouverture suivent mieux la réalité du bâtiment."),
            ("Gestion plus simple", "Le gestionnaire obtient une logique d'entrée plus facile à exploiter."),
        ],
        "cta_title": "Décrivez votre entrée et votre immeuble",
        "cta_copy": "Indiquez le nombre d'entrées, le type d'immeuble et ce que vous voulez améliorer. On vous aidera à cadrer la bonne solution.",
        "cta_label": "Obtenir une soumission",
        "service_key": "intercom-systems",
    },
    "lp-commercial-wifi-audit": {
        "path": "/fr/lp/audit-wifi-commercial/",
        "title": "Audit WiFi commercial | Opticable",
        "desc": "Évaluation WiFi pour bureaux, commerces et immeubles commerciaux avec zones problématiques et plan de correction.",
        "eyebrow": "WiFi commercial",
        "headline": "Audit WiFi commercial pour zones faibles, coupures et couverture inégale",
        "intro": "Si le WiFi coupe, ralentit ou ne couvre pas les bonnes zones, le problème n'est pas toujours la borne elle-même. On aide à cadrer les vraies causes avant de proposer la suite.",
        "panel_title": "Ce qu'on valide",
        "panel_copy": "Couverture, zones mortes, densité d'usagers, câblage, PoE, interférences et état du local réseau.",
        "items": [
            "Bureaux et salles de réunion",
            "Commerces et points de vente",
            "Aires communes et zones partagées",
            "Bâtiments occupés avec contraintes réelles",
        ],
        "benefits": [
            ("Diagnostic plus juste", "On évite de remplacer du matériel au hasard."),
            ("Portée mieux cadrée", "La suite du projet devient plus claire et plus utile."),
            ("Base plus propre", "Le WiFi est traité avec le réseau et le câblage, pas isolé du reste."),
        ],
        "cta_title": "Expliquez où le WiFi vous nuit",
        "cta_copy": "Dites-nous le type de site, les zones problématiques et le nombre d'usagers. On vous dira comment cadrer la bonne prochaine étape.",
        "cta_label": "Demander une évaluation",
        "service_key": "commercial-wifi-installation",
    },
}


GUIDE_INDEX_PAGE = {
    "path": "/fr/guides/",
    "title": "Guides de planification technologique | Opticable",
    "desc": "Guides pratiques pour cadrer un projet de contrôle d'accès, intercom, câblage, caméras et infrastructure réseau.",
    "eyebrow": "Guides",
    "headline": "Guides de planification avant de demander une soumission",
    "intro": "Ces pages répondent aux questions qui reviennent avant une soumission : budget, choix de système, migration, remise en ordre et portée typique selon le projet.",
    "panel_title": "À qui ça sert",
    "panel_copy": "Aux gestionnaires, propriétaires, entreprises et équipes de projet qui veulent mieux cadrer une portée avant une visite de site ou une demande de prix.",
}
