PRAGMA defer_foreign_keys = on;

CREATE TABLE referral_cases_new (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  account_id INTEGER NOT NULL,
  referral_code_id INTEGER,
  referral_code TEXT NOT NULL,
  account_type TEXT NOT NULL CHECK (account_type IN ('client', 'partner')),
  status TEXT NOT NULL CHECK (status IN ('new', 'quoted', 'accepted', 'completed_paid', 'member_paid', 'void')),
  locale TEXT NOT NULL CHECK (locale IN ('en', 'fr')),
  referred_name TEXT NOT NULL,
  referred_email TEXT NOT NULL,
  referred_email_normalized TEXT NOT NULL,
  referred_phone TEXT,
  referred_company TEXT NOT NULL,
  referred_company_normalized TEXT,
  referred_project_notes TEXT,
  quote_reference TEXT,
  landing_path TEXT,
  landing_url TEXT,
  referrer_url TEXT,
  referrer_host TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_content TEXT,
  utm_term TEXT,
  referred_discount_percent INTEGER NOT NULL DEFAULT 0,
  referred_discount_cap_cents INTEGER NOT NULL DEFAULT 0,
  quoted_subtotal_cents INTEGER,
  reward_policy_type TEXT NOT NULL CHECK (reward_policy_type IN ('client_credit', 'partner_fixed')),
  reward_amount_cents INTEGER,
  reward_generated_at TEXT,
  completed_paid_at TEXT,
  void_reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  manual_reward_amount_cents INTEGER,
  manual_reward_note TEXT,
  FOREIGN KEY (account_id) REFERENCES referral_accounts(id) ON DELETE CASCADE,
  FOREIGN KEY (referral_code_id) REFERENCES referral_codes(id) ON DELETE SET NULL
);

INSERT INTO referral_cases_new (
  id,
  account_id,
  referral_code_id,
  referral_code,
  account_type,
  status,
  locale,
  referred_name,
  referred_email,
  referred_email_normalized,
  referred_phone,
  referred_company,
  referred_company_normalized,
  referred_project_notes,
  quote_reference,
  landing_path,
  landing_url,
  referrer_url,
  referrer_host,
  utm_source,
  utm_medium,
  utm_campaign,
  utm_content,
  utm_term,
  referred_discount_percent,
  referred_discount_cap_cents,
  quoted_subtotal_cents,
  reward_policy_type,
  reward_amount_cents,
  reward_generated_at,
  completed_paid_at,
  void_reason,
  created_at,
  updated_at,
  manual_reward_amount_cents,
  manual_reward_note
)
SELECT
  id,
  account_id,
  referral_code_id,
  referral_code,
  account_type,
  CASE WHEN status = 'won' THEN 'accepted' ELSE status END,
  locale,
  referred_name,
  referred_email,
  referred_email_normalized,
  referred_phone,
  referred_company,
  referred_company_normalized,
  referred_project_notes,
  quote_reference,
  landing_path,
  landing_url,
  referrer_url,
  referrer_host,
  utm_source,
  utm_medium,
  utm_campaign,
  utm_content,
  utm_term,
  referred_discount_percent,
  referred_discount_cap_cents,
  quoted_subtotal_cents,
  reward_policy_type,
  reward_amount_cents,
  reward_generated_at,
  completed_paid_at,
  void_reason,
  created_at,
  updated_at,
  manual_reward_amount_cents,
  manual_reward_note
FROM referral_cases;

DROP TABLE referral_cases;
ALTER TABLE referral_cases_new RENAME TO referral_cases;

CREATE INDEX referral_cases_account_idx
  ON referral_cases(account_id, created_at DESC);

CREATE INDEX referral_cases_status_idx
  ON referral_cases(status, created_at DESC);

CREATE INDEX referral_cases_email_idx
  ON referral_cases(referred_email_normalized, created_at DESC);
